package com.capitolcamp.historicmarkers.domain;

// Generated Oct 23, 2012 12:55:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status")
@XmlRootElement
public class Status implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3452352001012858889L;
	private Account account;
	private int accountId;
	private Date created;
	private String lastError;
	private Date lastUpdated;
	private String status;
	private int version;
	private String watchServer;

	public Status() {
	}

	public Status(final Account account, final String watchServer, final String status, final Date created,
			final Date lastUpdated) {
		this.account = account;
		this.watchServer = watchServer;
		this.status = status;
		this.created = created;
		this.lastUpdated = lastUpdated;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@XmlTransient
	public Account getAccount() {
		return this.account;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "account"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "account_id", unique = true, nullable = false)
	@XmlTransient
	public int getAccountId() {
		return this.accountId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	@XmlTransient
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "last_error", nullable = true, length = 255)
	public String getLastError() {
		return lastError;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	@Version
	@Column(name = "version", nullable = false)
	@XmlTransient
	public int getVersion() {
		return this.version;
	}

	@Column(name = "watch_server", nullable = false, length = 45)
	@XmlTransient
	public String getWatchServer() {
		return this.watchServer;
	}

	public void setAccount(final Account account) {
		this.account = account;
	}

	public void setAccountId(final int accountId) {
		this.accountId = accountId;
	}

	public void setCreated(final Date created) {
		this.created = created;
	}

	public void setLastError(final String lastError) {
		this.lastError = lastError;
	}

	public void setLastUpdated(final Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public void setStatus(final String status) {
		this.status = status;
	}

	public void setVersion(final int version) {
		this.version = version;
	}

	public void setWatchServer(final String watchServer) {
		this.watchServer = watchServer;
	}

}
